on:
  push:
    branches:
    - master
    paths:
    - 'lab03-nobel-laureates.Rmd'
name: Try Knitting
jobs:
  check-rmd:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Rmd Rendering
      run:  Rscript -e "rmarkdown::render('lab03-nobel-laureates.Rmd')"
