project:
  type: "website"
  output-dir: docs
  render:
    - "*.qmd"
    - "!private"
    - "!*-template.qmd"
    - "!*-wip.qmd"
    - "!*scraps.qmd"
    - "!weeks/06*/*"
    - "!weeks/07*/*"
    - "!weeks/08*/*"
    - "!weeks/09*/*"
    - "!weeks/10*/*"
    - "!weeks/11*/*"
    - "!weeks/12*/*"
    - "!weeks/13*/*"
    - "!weeks/14*/*"
    - "!handouts/*"

website:
  title: "DATA 202 (Wrangling and Analytics), Fall 2024"
  site-url: "https://cs.calvin.edu/courses/data/202/fsantos"
  navbar:
    right:
      - index.qmd
      - text: "Google Colab"
        href: "https://colab.research.google.com/"
      - text: "Moodle page"
        href: "https://moodle.calvin.edu/course/view.php?id=63709"
  sidebar:
    contents:
      - tools.qmd
      - section: "Projects"
        icon: "kanban"
        contents:
          - midterm-proj.qmd
          - final-proj.qmd
      - section: "Weeks"
        icon: "person-workspace"
        contents:
          - section: "01 - Introduction"
            href: weeks/01.qmd
            contents:
              - weeks/introduction.qmd
              - text: "09-06 Practice 1"
                href: https://colab.research.google.com/drive/1UigQ8CZaWPtrRVV6Iqqk2ikFAyh1bh4s?usp=drive_link
          - section: "02 - Wrangling 1"
            href: weeks/02.qmd
            contents:
              - text: "09-09 - Wrangling - basic operations"
                href: https://colab.research.google.com/drive/1TjnQfqofUG3yn4pJ1PVyC67o1i1vW_bU?usp=drive_link
              - text: "09-11 - Wrangling - selecting, filtering and deriving"
                href: https://colab.research.google.com/drive/1UVQBbO2OgWnCSbDR1E7kH5hEL55-MaWM?usp=sharing
              - text: "09-11 - Practice 3"
                href: https://colab.research.google.com/drive/1UVQBbO2OgWnCSbDR1E7kH5hEL55-MaWM?usp=sharing
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc_float: true
    toc-depth: 4
    toc-expand: 4
