project:
  type: "website"
  output-dir: docs
  render:
    - "*.qmd"
    - "!private"
    - "!*-template.qmd"
    - "!*-wip.qmd"
    - "!*scraps.qmd"
    - "!weeks/06*/*"
    - "!weeks/07*/*"
    - "!weeks/08*/*"
    - "!weeks/09*/*"
    - "!weeks/10*/*"
    - "!weeks/11*/*"
    - "!weeks/12*/*"
    - "!weeks/13*/*"
    - "!weeks/14*/*"
    - "!handouts/*"

website:
  title: "DATA 202 (Wrangling and Analytics), Fall 2024"
  site-url: "https://cs.calvin.edu/courses/data/202/fsantos"
  navbar:
    right:
      - index.qmd
      - text: "Google Colab"
        href: "https://colab.research.google.com/"
      - text: "Moodle page"
        href: "https://moodle.calvin.edu/course/view.php?id=63709"
  sidebar:
    contents:
      - tools.qmd
      - section: "Projects"
        icon: "kanban"
        contents:
          - midterm-proj.qmd
          - final-proj.qmd
      - section: "Weeks"
        icon: "person-workspace"
        contents:
          - section: "01 - Introduction"
            href: weeks/01.qmd
            contents:
              - weeks/introduction.qmd
              - text: "09-06 Practice 1"
                href: https://colab.research.google.com/drive/1UigQ8CZaWPtrRVV6Iqqk2ikFAyh1bh4s?usp=drive_link
          - section: "02 - Wrangling 1"
            href: weeks/02.qmd
            contents:
              - text: "09-09 - Wrangling - basic operations"
                href: https://colab.research.google.com/drive/1TjnQfqofUG3yn4pJ1PVyC67o1i1vW_bU?usp=drive_link
              - text: "09-11 - Wrangling - selecting, filtering and deriving"
                href: https://colab.research.google.com/drive/1UVQBbO2OgWnCSbDR1E7kH5hEL55-MaWM?usp=sharing
              - text: "09-11 - Practice 2"
                href: https://colab.research.google.com/drive/130Dwri7iNFNan1zIYZlCz-6QXHSfKPg_?usp=sharing
          - section: "03 - Wrangling 2"
            href: weeks/03.qmd
            contents:
              - text: "09-16 - Wrangling - reshaping and dealing with strings"
                href: https://colab.research.google.com/drive/12ORcZA7onrQslYURFjChuc6MYyG8LWMP?usp=sharing
              - text: "09-18 - Wrangling - joining"
                href: https://colab.research.google.com/drive/1s44dqZlRCc229SBFJpddKFAba5iBWUU8?usp=sharing
              - text: "09-11 - Practice 3"
                href: https://colab.research.google.com/drive/1S0jGWcAJTNc8iCdGgpUt1kjD_LkSCyTA?usp=sharing
          - section: "04 - Visualization 1"
            href: weeks/04.qmd
            contents:
              - text: "09-23 - Visualization - grammar of graphics"
                href: https://colab.research.google.com/drive/1c_PcQ_7UxLMwz6wlOzikuBBCuYqDc_67?usp=sharing
              - text: "09-25 - Visualization - plot zoo"
                href: https://colab.research.google.com/drive/10qu_sXtcolQzgilUReR6m6cP0LbBpfdH?usp=sharing
              - text: "09-27 - Practice 4"
                href: https://colab.research.google.com/drive/1xYy9wBpGs4kp3jA7aPnV_8r3lXYZZcw2?usp=sharing
          - section: "05 - Visualization 2"
            href: weeks/05.qmd
            contents:
              - text: "09-30 - Visualization - design and critique"
                href: https://colab.research.google.com/drive/1DnOEDVaqv2DeMOfuKxBG9ZJE-60Fzzq4?usp=sharing
              - text: "10-02 - Visualization - interactivity and sonification"
                href: https://colab.research.google.com/drive/1V1wCmst19uHIXyFNGD3osYVnlY_xWsjc?usp=sharing
              - text: "10-04 - Practice 5"
                href: https://colab.research.google.com/drive/1FtrglGKne7ec9Iy72j3zozzXTX-vmBsV?usp=sharing
          - section: "06 - Modeling basics"
            href: weeks/06.qmd
            contents:
              - text: "10-07 - Model types, definitions, k-nearest neighbors"
                href: https://colab.research.google.com/drive/1Jp160CBPO1AFwq7AsCzF9T-v7cTQ_Lcz?usp=sharing
              - text: "10-09 - Preprocessing"
                href: https://colab.research.google.com/drive/12QWZfoT2dSyikvQS_-H9RmAES5YyjjfP?usp=sharing
              - text: "10-11 - Practice 6"
                href: https://colab.research.google.com/drive/165jV8Bkh61_hwnhZa_nQVszajJcG8Gnn?usp=sharing
          - section: "07 - Linear models"
            href: weeks/07.qmd
            contents:
              - text: "10-14 - Linear regression"
                href: https://colab.research.google.com/drive/19wL6Drari00qrcmmdSJdd8aPpBnRKKrf?usp=sharing
              - text: "10-16 - Logistic regression"
                href: https://colab.research.google.com/drive/1Bcn47spCJZXgk4QtSOWWYimfiE2Vbl_Y?usp=sharing
              - text: "10-18 - Practice 7"
                href: https://colab.research.google.com/drive/1SGgPs1qI8S_CY9kjXM8fx0CjcHDFZ8mh?usp=sharing
          - section: "08 - Regularization and Trees"
            href: weeks/08.qmd
            contents:
              - text: "10-28 - Regularization and Cross-Validation"
                href: https://colab.research.google.com/drive/1nief3XbIWtMmbyr85pDa5vKY6wrKRaxQ?usp=sharing
              - text: "10-30 - Decision trees"
                href: https://colab.research.google.com/drive/1wyCpLhogbcTt-_0_XCRbdv862ej84e5g?usp=sharing
              - text: "10-18 - Practice 8"
                href: https://colab.research.google.com/drive/1S37V9nXhsC-p0XjMiBNo7K1ZcWcCpbsl?usp=sharing
          - section: "09 - Ensembles and Probability Scores"
            href: weeks/09.qmd
            contents:
              - text: "11-04 - Bagging, boosting and stacking"
                href: https://colab.research.google.com/drive/19p7xD3zKRERo-cEQae3tZTwvmAjwXmdM?usp=sharing
              - text: "11-06 - Probability scores and ROC"
                href: https://colab.research.google.com/drive/1w3d83FwBAUgNF_q8XBmLSBsHemTihnx3?usp=sharing
              - text: "11-08 - Practice 9"
                href: https://colab.research.google.com/drive/1F1O_PYjUnDQURAGwk4lGqxnp_b5RBJ58?usp=sharing
          - section: "10 - Unsupervised Learning"
            href: weeks/10.qmd
            contents:
              - text: "11-11 - PCA"
                href: https://colab.research.google.com/drive/1ZyLyk56JyjclSjTNYZSUeVMxsqGeNxaw?usp=sharing
              - text: "11-13 - Clustering"
                href: https://colab.research.google.com/drive/1MBku9q4udR2v0_rVXdCgtSIEMKuUWHp7?usp=sharing
              - text: "11-15 - Practice 10"
                href: https://colab.research.google.com/drive/1h0Y9pzR6vnwdAGPU3aIPxkAddj2zapwt?usp=sharing
          - section: "11 - Time-series and missing data"
            href: weeks/11.qmd
            contents:
              - text: "11-18 - Time-series"
                href: https://colab.research.google.com/drive/1vy5tPBxavtGetpZlJBtm1CVpxJnaZMzG?usp=sharing
              - text: "11-20 - Missing data"
                href: https://colab.research.google.com/drive/1Xx6_bakCdluhPxhDcew1L0Fjo3mirVag?usp=sharing
              - text: "11-22 - Practice 11"
                href: https://colab.research.google.com/drive/1mWS9khdBiB12NYokLxsolwAE63SKgQXS?usp=sharing
          - section: "12 - Fairness"
            href: weeks/12.qmd
            contents:
              - text: "11-28 - Fairness"
                href: https://colab.research.google.com/drive/1cSRieuZXn4_ilJUzubYhfqcUeCx0akcv?usp=sharing
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc_float: true
    toc-depth: 4
    toc-expand: 4
