project:
  type: "website"
  output-dir: docs
  render:
    - "*.qmd"
    - "!private"
    - "!*-template.qmd"
    - "!*-wip.qmd"
    - "!*scraps.qmd"
    - "!slides/02*/*"
    - "!slides/03*/*"
    - "!slides/04*/*"
    - "!slides/05*/*"
    - "!slides/06*/*"
    - "!slides/07*/*"
    - "!slides/08*/*"
    - "!slides/09*/*"
    - "!slides/10*/*"
    - "!slides/11*/*"
    - "!slides/12*/*"
    - "!slides/13*/*"
    - "!slides/14*/*"
    - "!handouts/02*/*"
    - "!handouts/03*/*"
    - "!handouts/04*/*"
    - "!handouts/05*/*"
    - "!handouts/06*/*"
    - "!handouts/07*/*"
    - "!handouts/08*/*"
    - "!handouts/09*/*"
    - "!handouts/10*/*"
    - "!handouts/11*/*"
    - "!handouts/12*/*"
    - "!handouts/13*/*"
    - "!handouts/14*/*"

website:
  title: "DATA 202 (Wrangling and Analytics), Fall 2024"
  site-url: "https://cs.calvin.edu/courses/data/202/fsantos"
  navbar:
    right:
      - index.qmd
      - text: "RStudio"
        href: "https://r.cs.calvin.edu/"
  sidebar:
    contents:
      - tools.qmd
      - section: "Projects"
        icon: "kanban"
        contents:
          - midterm-proj.qmd
          - final-proj.qmd
      - auto: "slides/"
        icon: "person-workspace"
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc_float: true
    toc-depth: 4
    toc-expand: 4
