project:
  type: "website"
  output-dir: docs
  render:
    - "*.qmd"
    - "!private"
    - "!*-soln.qmd"
    - "!*-template.qmd"
    - "!*-wip.qmd"
    - "!*scraps.qmd"
  post-render: "rsync -r static/ _site"

website:
  title: "DATA 202 (Wrangling and Analytics), Spring 2024"
  site-url: "https://cs.calvin.edu/courses/data/202/fsantos"
  navbar:
    right:
      - index.qmd
      - text: "RStudio"
        href: "https://r.cs.calvin.edu/"
  sidebar:
    contents:
      - section: "Notes"
        icon: "pencil"
        contents: "notes/*"
      - section: "Classes"
        icon: "book-half"
        contents:
          - section: "Week 1"
            contents: "classes/week1/*"
      - section: "Projects"
        icon: "kanban"
        contents:
          - midterm-proj.qmd
          - final-proj.qmd
      - section: "Concepts"
        icon: "book-half"
        contents:
        - "concepts/1intro.qmd"
        - section: "2. Wrangling"
          contents: "concepts/2wrangling/*"
        - section: "3. Visualization"
          contents: "concepts/3visualization/*"
        - section: "4. Modeling"
          contents: "concepts/4modeling/*"

  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc_float: true
    toc-depth: 4
    toc-expand: 4
