---
title: "Homework 04 - Wrangling Spatial Data"
author: "Author Goes Here"
output:
  prettydoc::html_pretty
#knit: pagedown::chrome_print
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
dennys <- read_rds("data/dennys.rds")
laquinta <- read_rds("data/laquinta.rds")
states <- read_csv("data/states.csv", col_types = cols(
  name = col_character(),
  abbreviation = col_character(),
  area = col_double()
))
```

### Exercise 1


### Exercise 2


### Exercise 3


### Exercise 4


### Exercise 5


```{r}
# Implementation from dsbox
haversine <- function(long1, lat1, long2, lat2) {
  # convert to radians
  long1 = long1 * pi / 180
  lat1  = lat1  * pi / 180
  long2 = long2 * pi / 180
  lat2  = lat2  * pi / 180
  
  # Earth mean radius in km (WGS84 ellipsoid)
  R = 6371.009
  
  a = sin((lat2 - lat1)/2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1)/2)^2
  d = R * 2 * asin(sqrt(a))
  # Return the distance in km
  d
}
```


### Exercise 6


### Exercise 7


### Exercise 8

```{r}
compute_closest_dennys <- function(the_state) {
  dn_state <- dennys %>% 
    filter(state == the_state)
  lq_state <- laquinta %>% 
    filter(state == the_state)
  
  # join to get all possible pairings

  # compute distances
  
  # compute distance to closest Denny's for each La Quinta location.

  return(dist_to_closest)
}
```


### Exercise 9


### Exercise 10


### Exercise 11


## Wrap-Up

### GitHub permalink

### Partners

### Reflections

