---
title: "DATA 202 Calendar -- Fall 2019"
author: ""
date: ""
output:
  html_document:
    includes:
      before_body: header.shtml
---

```{r, setup, include = FALSE}
if (! require(devtools)) {
  install.packages("devtools")
}

if (! require(calendar)) {
  devtools::install_github("rpruim/calendar")
}
library(magrittr)
```

### All Topics

* [Linear Regression](topics/linreg.html)
* [Data Wrangling](topics/wrangling.html)
* [Classification](topics/classification.html)
* [EDA and Unsupervised Learning](topics/eda_unsupervised.html)
* [Recommender Systems and Reinforcement Learning](topics/actions.html)
* [SQL](topics/sql.html)

#### Key

<!-- calendar converts Class:: into approprate span -->

* <span class ="Topic">Topic of the day</span>
* <span class ="Reading">Reading assignment</span>
* <span class ="Lab">Lab</span>
* <span class ="Due">Due date</span>
* <span class ="Note">Note</span>

----------

```{r, results = 'asis', echo = FALSE}
daily2html(
  "daily.txt", 
  start = lubridate::mdy("09/03/2019"), 
  end   = lubridate::mdy("12/09/2019"), 
  show = 2:6, 
  items = c("Topic", "Lab", "Read", "R", "Due", "Note")) %>%
  cat()
```

