---
title: "Intro"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
library(reticulate)
reticulate::py_run_string(r"--(
import pandas as pd
import plotly.express as px
gapminder = px.data.gapminder().sort_values('year')
health_and_wealth_2007 = px.data.gapminder(year=2007).reset_index(drop=True)
)--")
```


## Warmup

### Running Python Code

Write the Python code required to add two plus two:

```{python two-plus-two, exercise=TRUE}

```

### Dataset info

Run each of these exercises to explore different ways of seeing what's in a data frame.

Write a comment line (`# `) above each one to document what you observe that it does.

```{python df-info-1, exercise=TRUE, exercise.lines = 4}
# This shows the first and last rows in the data frame.
health_and_wealth_2007
```

```{python df-info-2, exercise=TRUE, exercise.lines = 4}
# This ...
health_and_wealth_2007.info()
```

```{python df-info-3, exercise=TRUE, exercise.lines = 4}
# ...
health_and_wealth_2007.head()
```

```{python df-info-4, exercise=TRUE, exercise.lines = 4}
# ...
health_and_wealth_2007.shape[0]
```



### Making a Plot

<script type="text/javascript" src="https://cdn.plot.ly/plotly-2.14.0.min.js"></script>
<script>
define('plotly', [], function() { return window.Plotly});
</script>

Here's the first step in replicating Rosling's "Health and Wealth" plot from the video.

```{python}
#health_and_wealth = px.data.gapminder(year=2007)
#px.scatter(health_and_wealth, x="gdpPercap", y="lifeExp")
```

**Exercise**: Use color to show which continent each country is in. To do this, add a mapping from `color` to `continent`.

```{python plot-gdp, exercise=TRUE, exercise.lines = 5}
health_and_wealth = px.data.gapminder(year=2007)
px.scatter(health_and_wealth, x="gdpPercap", y="lifeExp")
```

```{python plot-gdp-solution}
health_and_wealth = px.data.gapminder(year=2007)
px.scatter(health_and_wealth, x="gdpPercap", y="lifeExp", color="continent")
```


## Styling and labeling plots

Modify the following plot to:

1. Add labels for the `x` and `y` axes.
2. Add a `title`
3. Set the `color` of the line to `green`. (Is it green now?)

```{python line-plot-style, exercise=TRUE}
countries = ["United States"]
filtered_countries = gapminder[gapminder['country'].isin(countries)]
px.line(filtered_countries, x="year", y="lifeExp")
```

## Mapping vs Faceting

Consider this plot:

```{python line-plot, exercise=TRUE}
countries = [
  "China", "India", "United States",
  "Indonesia", "Brazil", "Pakistan",
  "Bangladesh", "Nigeria", "Japan"]

filtered_countries = gapminder[gapminder['country'].isin(countries)]
px.line(filtered_countries, x="year", y="lifeExp")
```

Notice that we're filtering to only include rows where the `country` is in the list of `countries` that we made.
This is so that we don't have so many different colors or facets in these graphs.

1. Explain to your partner why the plot has the shape it does. (If you're not sure, click `gapminder` in  the Environment pane and think about how you'd draw a line with that data.)
2. Map `color` to `country`. Describe the plot you get.
3. Now *facet* by country instead.
