---
title: "Quiz 10 Materials"
author: "K Arnold"
date: "11/4/2020"
output:
  html_document:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
```

```{r utilities, echo=FALSE}
add_predictions <- function(data, ...) {
  imap_dfr(
    rlang::dots_list(..., .named = TRUE),
    function(model, model_name) {
      model %>%
        predict(data) %>%
        bind_cols(data) %>%
        mutate(model = !!model_name)
    }
  )
}

sweep_model <- function(model, var_to_sweep, sweep_min, sweep_max, ...) {
  X <- expand_grid(!!enquo(var_to_sweep) := seq(sweep_min, sweep_max, length.out = 500), ...)
  model %>% 
    predict(X) %>% 
    bind_cols(X)
}

linear_reg <- function(engine = "lm", ...) {
  parsnip::linear_reg(...) %>% set_engine(engine)
}

decision_tree <- function(mode = "regression", engine = "rpart", ...) {
  parsnip::decision_tree(mode = "regression", ...) %>%
    set_engine(engine)
}
```


```{r model-comparison, fig.width=8, fig.height=4}
set.seed(0)
data <- tibble(
  x = seq(0, 1, length.out = 100),
  y = .1 * rnorm(100) + (x > .25) - (x > .5) + (x > .75)
)

models <- tribble(
  ~name, ~spec,
  "model1", linear_reg(),
  "model2", decision_tree(tree_depth = 1),
  "model3", decision_tree(tree_depth = 30)
)

models %>% 
  rowwise(name) %>% 
  mutate(fitted = list(spec %>% fit(y ~ x, data = data))) %>% 
  summarize(fitted %>% predict(data) %>% bind_cols(data) %>% mutate(model_name = name), .groups = "drop") %>% 
  ggplot(aes(x = x, y = y)) +
    geom_point() +
    geom_line(aes(y = .pred), color="red") +
    facet_wrap(vars(model_name))
```


```{r data-comparison, fig.width=8, fig.height=4}
set.seed(0)
tibble(
  x = seq(0, 1, length.out = 100),
  y1 = .1 * rnorm(100) + (x > .25) - (x > .5) + (x > .75),
  y2 = .1 * rnorm(100) + x,
  y3 = (.1 * rnorm(100) + -4 * x + 5 * x*x) / 2 + .5
) %>% 
  pivot_longer(-x) %>% 
  mutate(name = str_remove(name, "y")) %>% 
  ggplot(aes(x = x, y = value)) +
  geom_point() +
  facet_wrap(vars(name))



```

