---
title: 'Lab 12: Clustering'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(patchwork)
theme_set(theme_bw())
```

```{r load-data, echo=FALSE}
data(ames, package = "modeldata")
#ames <- AmesHousing::make_ames()
ames_all <- ames %>%
  filter(Gr_Liv_Area < 4000, Sale_Condition == "Normal") %>%
  mutate(across(where(is.integer), as.double)) %>%
  mutate(Sale_Price = Sale_Price / 1000)
rm(ames)
```

## Find Clusters

```{r make-clusters}
set.seed(20201120)
clustering_results <- 
  recipe( ~ Latitude + Longitude, data = ames_all) %>% 
  prep() %>% 
  bake(new_data = ames_all) %>% 
  kmeans(nstart = 4, centers = 3)

ames_with_clusters <- ames_all %>% 
  mutate(cluster = as.factor(clustering_results$cluster))
```


```{r glance-clustering-results}
glance(clustering_results)
tidy(clustering_results)
```

## Plot Clusters

```{r cluster-plots}
latlong_plot <- 
  ggplot(ames_with_clusters, aes(x = Latitude, y = Longitude, color = cluster, shape = cluster)) +
    geom_point(alpha = .5)

year_area_plot <- 
  ggplot(ames_with_clusters, aes(x = Gr_Liv_Area, y = Year_Built, color = cluster, shape = cluster)) +
    geom_point(alpha = .5)

latlong_plot + year_area_plot + 
  plot_layout(guides='collect') & theme(legend.position = "bottom")
```

## Plot Sale Price by Cluster

Do the patterns captured by these clusters also happen to relate to sale price?

```{r sale-price-by-cluster, fig.asp=0.4}
ames_with_clusters %>% 
  ggplot(aes(x = Sale_Price, y = cluster)) + geom_boxplot()
```
