---
title: "BigQuery"
author: "K Arnold"
date: "11/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

We can access Google BigQuery using the [bigrquery](https://github.com/r-dbi/bigrquery) package.

Examples:

* [NFL Play-by-Play](https://calogica.com/r/bigquery/2020/08/18/r-bigquery.html)
* [NYC Yellow-Cab Trips](https://cfss.uchicago.edu/notes/sql-databases/#interacting-with-google-bigquery-via-dplyr)
* [FiveThirtyEight analysis of subreddit relationships](https://github.com/fivethirtyeight/data/tree/master/subreddit-algebra)

We need to tell BigQuery which project to bill:

```{r}
billing_project <- "calvindsdev"
```

Several public datasets are available:

```{r}
taxi <- DBI::dbConnect(
  bigrquery::bigquery(),
  project = "nyc-tlc",
  dataset = "yellow",
  billing = billing_project
)
```

```{r}
trips <- taxi %>% tbl("trips")
trips %>% glimpse()
trips
```

```{r}
trips %>% 
  filter(year(pickup_datetime) == 2014) %>% 
  group_by(month = month(pickup_datetime)) %>% 
  summarize(n = n())
```


```{r}
trips %>% 
  filter(year(pickup_datetime) == 2014L) %>% 
  group_by(month = month(pickup_datetime)) %>% 
  summarize(n = n()) %>% 
  show_query()
```

```{r}
trips %>% 
  filter(year(pickup_datetime) == 2014L) %>% 
  mutate(month = month(pickup_datetime)) %>% 
  count(month) %>% 
  show_query()
  
```

