---
title: "Covid deaths"
---


```{r setup, message=FALSE}
library(coronavirus) # devtools::install_github("RamiKrispin/coronavirus")
library(tidyverse)
library(lubridate)
library(glue)
library(gapminder)
```

```{r}
# coronavirus::update_dataset()
cases <- coronavirus::coronavirus
```

```{r}
cases %>% summarise(max(date))
```


```{r}
cases %>% 
  group_by(type) %>% 
  summarize(n = n())
```

```{r}
cases %>% 
  filter(type == "death", cases < -100)
```
```{r}
cum_cases <-cases %>% 
  filter(province == "") %>% 
  group_by(country, type) %>% 
  mutate(cum_cases = cumsum(cases))
  #group_by(country) %>% 
  #filter(type == "death") %>%
  #mutate(max_cum_cases = max(cum_cases)) %>% 
  #ungroup()

cum_cases %>% glimpse()

cum_cases %>% 
  #filter(max_cum_cases > 20000) %>% 
  filter(country %in% c("US", "United Kingdom", "Spain", "Brazil")) %>% 
  #filter(country == "United Kingdom") %>% 
  ggplot(aes(x = date, y = cum_cases, color = type)) +
    geom_line() +
    facet_wrap(~ country, nrow = 3, scales = "free_y")
```


```{r}
cases %>% 
  filter(type == "death") %>%
  group_by(country) %>% 
  mutate(max_deaths = max(cases)) %>% 
  ungroup() %>% 
  filter(max_deaths > 1000) %>% 
  filter(cases > 0) %>% 
  ggplot(aes(x = date, y = cases, color = country)) +
    geom_line()
```

