---
title: "Inference"
author: "K Arnold"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(infer)
```


Potential Example:

<https://www.tidymodels.org/learn/statistics/infer/>


```{r}
#data(ames, package = "modeldata")
ames <- AmesHousing::make_ames()
ames_all <- ames %>%
  filter(Gr_Liv_Area < 4000, Sale_Condition == "Normal") %>%
  mutate(across(where(is.integer), as.double)) %>%
  mutate(Sale_Price = Sale_Price / 1000)
rm(ames)
```


```{r}
mean_samples <- ames_all %>% 
  specify(response = Sale_Price, explanatory = Neighborhood) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "F")

mean_samples %>% 
  visualise()
```


```{r}
boot <- ames_all %>% 
  specify(response = Sale_Price, explanatory = Gr_Liv_Area) %>% 
  generate(reps = 100, type = "bootstrap") %>% 
  calculate(stat = "correlation")
```

```{r}
infer::visualise(boot)
```

```{r}
ames_all %>% 
  ggplot(aes(x = Full_Bath, y = Sale_Price)) +
  geom_point() +
  geom_smooth(method = "lm")
```


```{r}
point_estimate <- ames_all %>% 
  specify(Sale_Price ~ Full_Bath) %>% 
  calculate("slope")
point_estimate

ames_all %>% 
  specify(Sale_Price ~ Full_Bath) %>% 
  hypothesise(null = "independence") %>% 
  generate(reps = 1000, type = "permute") %>% 
  calculate("slope") %>% 
  visualize() +
  shade_p_value(obs_stat = point_estimate, direction = "two-sided")
```

```{r}
ames_all %>% 
  ggplot(aes(x = Bsmt_Half_Bath, y = Sale_Price, color = Bsmt_Full_Bath > 0)) +
  geom_point() + geom_smooth(method="lm")
```


```{r all_features, fig.width=10, fig.height=10, fig.fullwidth=TRUE}
ames_all %>% 
  # Pivot all of the numeric variables except for the outcomes and residuals.
  pivot_longer(c(where(is.numeric) & !any_of(c("Sale_Price", ".pred", "resid")))) %>% 
  # Plot!
  ggplot(aes(x = value, y = Sale_Price)) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_wrap(vars(name), scales = "free")
```

