---
title: "Grade Analysis"
author: "K Arnold"
date: "12/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
gradebook <- readxl::read_excel("../fa20/20FA DATA-202-A Grades.xlsx", na = "-")
gradebook
```

```{r}
grades <- gradebook %>%
  select(`First name`, `Last name`, `Email address`, matches("^Assignment.*Real\\)$")) %>% 
  janitor::clean_names()
```

Find zero grade items.

```{r}
grades %>% 
  filter(!is.na(assignment_final_project_real)) %>% 
  pivot_longer(-c(1:3)) %>% 
  filter(value == 0)
```

```{r}
gradebook %>%
  janitor::clean_names() %>%
  ggplot(aes(x = parse_number(course_total_percentage), y=0)) + ggbeeswarm::geom_beeswarm(groupOnX = FALSE)
```

```{r}
official_grades <- read_csv('../fa20/submitted_grades.csv') %>% 
  janitor::clean_names() %>% 
  transmute(student_id, student_name, submitted_grade = final_grade)
official_grades
```


```{r}
gradebook %>% select(
  student_id = `ID number`,
  `Course total (Letter)`) %>% 
  mutate(student_id = as.numeric(student_id)) %>% 
  full_join(official_grades, by = "student_id") %>% 
  janitor::clean_names() %>% 
  mutate(match = course_total_letter == submitted_grade) %>% filter(!match) %>% 
  filter(course_total_letter != "F") %>% 
  select(Name = student_name, ID = student_id, `New Grade` = course_total_letter, `Old Grade` = submitted_grade) %>% 
  knitr::kable()
```

