---
title: "Lab 11: Classification"
output: github_document
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(reticulate)
# Avoid the Python crash
py_run_string("import matplotlib.pyplot as plt; plt.switch_backend('agg')")
theme_set(theme_bw())
options(dplyr.summarise.inform = FALSE) # silence a warning message
```

```{python python-setup, echo=FALSE}
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score
```



## Acquiring Data

```{r download-data, echo=TRUE}
data_filename <- "data/autism.csv"
if (!file.exists(data_filename)) {
  dir.create("data")
  download.file("https://doi.org/10.1371/journal.pcbi.1005385.s001", data_filename)
}
```

```{r read-data, echo=TRUE}
col_names <- names(read_csv(data_filename, n_max = 1, col_types = cols(.default = col_character())))
autism <- read_csv(data_filename, skip = 2, col_names = col_names, col_types = cols(
  .default = col_double(),
  Group = col_character()
))
```

```{python, echo=TRUE}
autism = r.autism
```

## EDA


## Modeling

