---
title: "HW 6: Vis Reproduction, Predictive Modeling"
output: 
  tufte::tufte_html:
    css: ../hw.css
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggformula)
library(plotly)
```

## Goals

This homework has two goals:

* Take the first steps towards reproducing a data visualization
* Try out some predictive modeling.

## Reproducing a Data Visualization

Our goal for the Midterm will be to reproduce and critically analyze a data visualization that you find.
We want to be able to guide you towards an appropriate visual to choose, so this
homework gives an opportunity to do some initial work and then check in before
we do the whole thing.

First, find the data for the chart that you picked in Discussion 3. See that
assignment for details on what sort of chart to choose.

* If you were advised there to find a different chart, please quickly run your new choice by me (on Teams).
* If you're having trouble finding the data, reach out ASAP or find some comparable data,
  or find a different chart (and run it by me).

Then, make a first shot at replicating the visual.

The goal is a solid attempt, not the finished product. The bare minimum
submission consists of:

* An empty plot with the right axis labels
* Some concrete questions that will help you take the next steps.

If this proves too easy, consider challenging yourself with a more interesting chart.

### Submission

* Place your code in an R Markdown file in your `datavis` repo.
* If your data is less than 10 MB, place it in a `data` folder in your repo
(just like in our past assignments).
* If your data is larger or has distribution restrictions that keep you from sharing it,
place detailed instructions for how to get the data (e.g., the exact URLs to go to)
at the top of your R Markdown file, and do not check in the data file.

## Predictive Modeling

Try out Google's Teachable Machine. You may use either [v1](https://teachablemachine.withgoogle.com/v1/)
(more playful) or [v2](https://teachablemachine.withgoogle.com/) (more practical).

If you're having trouble running Teachable Machine on your computer, please let me know ASAP.

Answer the following questions in the assignment on Moodle:

1. Is this a classification or regression model?

2. Train the model to successfully distinguish two different things. What did you
   train it to distinguish?
   
3. Try to find a systematic way to fool your trained model, i.e., where the model
   consistently gets something wrong (despite being right other times).
   
   * What did you find that fools it?
   * Can you find situations where it is *confidently* wrong? *un-confidently* wrong?

4. Give a plausible explanation for why the model might make incorrect predictions.
   Your answer does not need to be technically correct, but it should properly
   use the terms "training data" (or "training set") and "generalize" / "generalization".
