---
title: "Q&A 1"
format: revealjs
editor: visual
---

## Choice of R

- What is the industry standard language for data science? What is the industry standard computer for data science?  
- Is R still the best language for data processing?  
- What other platforms are there for statistical analysis? Why are we using R?  

## Packages  

- If one were to RStudio locally rather than Calvin's server, what packages should they download?  
- How many packages are in existence? Could I make my own package?  

## Toolkit

- Do most data scientists use RStudio to write R code? Do they write R code using some other program?
- Why are R, RStudio, and R Markdown classified as three different things?  
- Can something like RStudio or R Markdown be implemented into another coding language?  
- How would R Studio function without R Markdown? (I still don't completely understand what R Markdown is, but I understand what it does.)  

## What is DS?  

- Why is Data Science not just part of under computer science?  
- What is the difference between data analytics and data science? Both seem to be about analyzing and deriving important information from the data.
- What does "modeling" mean in data science (as opposed to natural science)?

## Where are we going?  

- Will we be doing modeling?
- How advanced of statistics are we going to end up using?  


## Perspectives  
- how can hospitality extend beyond just being easily understood in data science? what would be an excellent demonstration of hospitality in this field of science.  
- I am interested to see how many aspects of our lives data science actually affects.  
- After watching the second video, I noticed that if people blindly believe in data and charts, but data analysts intentionally sift through the data during wrangling, then objective data wrangling becomes associated with justice.  
- I'm interested in learning more about Hans Rosling's work.  

## Logistics

- Are midterm and final projects done individually or group?
- Once I graduate from Calvin, can I access RStudio?
- Can we see the correct answer after getting the question wrong?  

## Memorizing

- What is the best way to memorize these functions? Or do you recommend we focus more on notes of functions rather than memorization at the moment?  
- What is the best way of retaining the information from these videos? Should we do practice problems related to them afterwards?  
- What functions are most important to know at the beginning of this course?  
- Are we expected to be able to write code similar to in the videos already?  

## Plotting

- Can we use `ggformula` that we're learning in stats class?
- Can we make animations?
- Can we make interactive plots?

## We'll get to it...  

- Why is a logarithmic scale helpful? It seems to me like that's just making the data more confusing and potentially misleading.  
- What other types of visualization of data will we use besides dot plots and line plots, if any?  
- How do I make a plot in R Studio?  
- Why is the package called "tidyverse"? Is the tidyverse package big or small as far as packages go?  
- I am struggling with understanding the basics of TidyVerse. Could you possibly help explain that to me? Could you also go over how objects work and the difference between vectors and other common objects   
  (matrices, arrays, and factors)?  
- In the future, will we be provided datasets to work along side the instructor so that we can get some hands on work in? 

## Piping

- Pipes? Huh?
- `|>` vs `%>%`?
- Should we pipe *everything*?


## Perspectives Discussion

- What's something you learned from reading other posts?
- What's some way that you'd want the Manifesto to be more specific (or different) related to this topic?
