---
title: "Q&A 2"
format: revealjs
editor: visual
---

## Technical

- Is there a reference sheet for all this?
- ggplot with more than one geom? Mapping globally vs locally?
- How do you change the color/size/font and other design aspects of graphs in R?

[https://github.com/erikgahner/awesome-ggplot2](awesome-ggplot2)

## ggplot vs ggformula

- Why `+` instead of `|>` or `%>%`?
- Do geom_ and gf_ plots look different? Why would a person use one of these function sets over another?

## Faceting

- How many facets are too much?
- What if you don't want the charts exactly the same? different aesthetic mappings etc?

## Plot types

- Should we memorize which plot types to use?
- If our data fits a graph type, will we ever get marked down because a different graph type could have been better?

## Art

- Could you make an "In the Barrel" that actually works?
- Is it possible, and if so, how do you create literal pictures/graphics in R rather than just graphs?

## History

Some of the examples that Prof VanderLinden uses date back 100s of years ago, which is really cool! I am curious when all of the different types of visualizations were organized and named and compared. Was it in the before or during the 1990s or more recent?

Are there people working on making new charts now?

## Other

Are there good colors to stick to? The cheat sheet has a lot of blue/red/yellow but that's partially because of it's color scheme.


When a person ever use geographic coordinates when not referring to geography?




"visualization relative percentages of a whole?" what does this mean?



We're taught early to always start at 0 on the y-axis, but that's not the case when the data is hard to represent with that kind of scale. In the video is shows that we need truncate based on context. What is the best way to provide that context if your goal is to have a singular graph tell a story as an advertisement per se, but do not want your audience thinking you are skewing the data to fit your storyline?


