---
title: "Q&A 4"
format: revealjs
editor: visual
---

## Unofficial Revision Policy

For *any* assignment:

- Come to office hours
- Convince me you learned from your feedback
- Get full credit

## Logistics and Project

> When we have our project going on does the homework and lab work lighten up a little bit so we aren't overwhelmed with all the work? 

## Overall

> I feel I understand the "join" code in paper, but I feel I need very close guides to do a real problem. I will like to practice more on this material if we are going to use this a lot in future days.

- What are the most common mistakes you see when it comes to joining tables?

## Types of Joins

- How can we easily tell when a left join or right join has been used by looking at a joined table?
- In what circumstances would you use left join vs right join? What is an easy way to differentiate them?
- Which type of join is used most often? 

## Keys 

- Must all keys be foreign or primary?
- I still have trouble differentiating between the two types of keys (primary and foreign). 

## Diagrams

- Can we make a schema on R? If not, how do we make one?

## Missing Values

> No specific question but going over handling NA values more could be good

