---
title: "Week 11"
format: revealjs
editor: visual
---

## Projects

> Whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable---if anything is excellent or praiseworthy---think about such things.\
> **Philippians 4:8**

## Inference, Prediction, or Forecasting?

::: {.incremental}

-   Is this customer likely to cancel our service?

-   What factors lead customers to cancel service?

-   If I add an additional bedroom, what difference will that make in my resale price?

-   How much will my home go up in value?

-   The home next door is about to go on the market; what will it sell for?

:::

## Prediction: Three Intuitions

-   A prediction competition

-   Programming by Demonstration

-   Risk Minimization

## Measuring Performance

::: {.incremental}

-   "The prediction was \$50 too low."

-   "The predictions were off by \$100 on average."

-   "The predictions were off by 5% on average."

-   "The model explained 90% of the variance."

:::

## Why Split Data?

## Code for Modeling

-   `tidymodels`: lots of different models, same code.

-   Even neural nets
