---
title: "Prayers for Data Science"
---

This semester, we pray according to this general pattern:

- **Monday**: for us as data scientists and citizens and neighbors
- **Wednesday**: for those affected by what we study
- **Friday**: lectio continua, open to what God will say. (This semester we will choose a reading from the week's Lectionary.)

Log:

### Week 1

- Monday: for knowledge and discernment in love, towards justice
    - Philippains 1:9-11
    - [Amos 5:14-15, 21-24 NRSV](https://www.biblegateway.com/passage/?search=Amos+5&version=NRSVUE&interface=print)
- Wednesday: for those affected by data-driven recommendations
    - [Philippains 4:8](https://www.biblegateway.com/passage/?search=phil+4%3A8&version=NIV&interface=print)
    - People watching to be able to discern what is true, honorable, and pure, especially when that's different than what grabs attention or agrees with assumptions
    - People creating videos to strive for what is just, right, commendable, especially when that's different than what will get rewarded by the recommendation algorithms
    - People building data-driven systems to make them in ways that bend towards justice.
- Friday: Psalm 124 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=156#psalm_reading)

### Week 2

- No class Monday (Labor Day)
- Wednesday: for humility as we consider the limitations of data science
    - "God opposes the proud but gives grace to the humble" (James 4:6, 1 Peter 5:5)
- Friday: Psalm 105 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=157#psalm_reading)
    - God works throughout history, over long periods of time. We prayed that we would be faithful in our small contributions and trust that God will work out his will in data science.

##  Week 3

- Monday: [Proverbs 12:15-20](https://www.biblegateway.com/passage/?search=proverbs%2012&version=NRSV&interface=print) (Truth)
  - That our minds not be deceitful (verse 20)
  - That we'd avoid confirmation bias and seek out good advice (verse 15)
  - *GitHub Copilot adds*: That we'd be careful with our words (verse 18)
- Wednesday: didn't prep a prayer.
- Friday: Psalm 149 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=158#psalm_reading)
  - We again prayed for humility in our work, and to trust that God will bring about what is ultimately right.

## Week 4

- Monday: We read the intro to "[Our World Belongs to God](https://www.crcna.org/welcome/beliefs/contemporary-testimony/our-world-belongs-god)"
- Wednesday: We read a bit from [How sounds can turn us on to the wonders of the universe | MIT Technology Review](https://www.technologyreview.com/2023/06/19/1074049/universe-sonification/) and reflected on accessible technology.
- Friday: Psalm 114 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=159#psalm_reading)

## Week 5

- Monday: We returned to the call to justice in [Amos 5](https://www.biblegateway.com/passage/?search=Amos+5&version=NIV&interface=print) and how this connects with how Prof Arnold ended up at Calvin.
- Wednesday: We prayed for those whose work is threatened by automated mimics, such as screenwriters--on the occasion of the [new WGA contract](https://www.engadget.com/the-wga-strike-ends-with-protections-against-ai-set-in-place-050019363.html)
- Friday: Philippians 2:1-13 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=161#epistle_reading)

## Week 6

- Monday: We read Section 4 from the [Belhar Confession](https://www.crcna.org/welcome/beliefs/contemporary-testimony/confession-belhar).
- Wednesday: We briefly discussed reidentification, using the figure from [this article](https://queue.acm.org/detail.cfm?id=2838930), and prayed for those whose privacy is threatened by data collection and aggregation.
  - For more on reidentification: watch the video on that page, read this [overview](https://georgetownlawtechreview.org/re-identification-of-anonymized-data/GLTR-04-2017/), or read [Sweeny's original paper](https://dataprivacylab.org/projects/identifiability/paper1.pdf)
- Friday: Psalm 19 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=162#psalm_reading)

## Week 7 and 8

- Monday: We prayed in lament for the conflict in Israel, the pain of indigenous people in our country's past, and the hottest summer on record
- Wednesday: We prayed for rest in our break.
- Friday (week 8) - Psalm 99 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=164#psalm_reading)

## Week 9

- Monday: had technical difficulties, so didn't actually get to prayer. Class emphasized potential for harm in data science, emphasized the need for wisdom.
- Wednesday: We showed some of the ways that predictive models can nudge human actions and opinions and prayed for protection.
- Friday - Psalm 90 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=165#psalm_reading)

## Week 10

- Monday: We prayed for insight as things get more difficult to see, like in data wrangling modeling. 
- Wednesday: We reflected briefly on the White House Executive Order on AI and prayed for our elected leaders.
- Friday: Psalm 34 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=166#psalm_reading)

## Week 11

- Monday: We prayed against greed and the love of money, with the help of [Hebrews 13](https://www.biblegateway.com/passage/?search=Hebrews+13%3A5-8&version=NIV&interface=print).
- Friday: Psalm 107 from the [Lectionary](https://lectionary.library.vanderbilt.edu/texts.php?id=167#psalm_reading)

## Misc

Things GitHub Copilot has suggested:

- We read [The Parable of the Polygons](https://ncase.me/polygons/) and prayed for the courage to act.
- [Deep Nostalgia](https://www.myheritage.com/deep-nostalgia).
- For praying for insight into the data, GitHub Copilot suggested that read [Psalm 119:18](https://www.biblegateway.com/passage/?search=Psalm+119%3A18&version=NIV&interface=print) and [1 Corinthians 13:12](https://www.biblegateway.com/passage/?search=1+Corinthians+13%3A12&version=NIV&interface=print).
