---
title: "Homework 3: Bike Sharing Data Wrangling"
author: "YOUR NAME"
output: prettydoc::html_pretty
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
# Import some functions from lubridate using less confusing names
get_year <- lubridate::year; get_month <- lubridate::month; get_day <- lubridate::day; get_weekday <- lubridate::wday

# Disable a warning message.
options(dplyr.summarise.inform = FALSE)
```


## Load Data

```{r load-data}
# Read the file, specifying data types for each column.
rides_2011 <- read_csv("data/rides_2011.csv.xz", col_types = cols(
  start_time = col_datetime(),
  duration = col_double(),
  rider_type = col_factor()
))
```

## Exercise 1

*Your narrative answer here.*

## Exercise 2

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
# Alternatively, use inline R code in your narrative answer.
```

*Your narrative answer here.*

## Exercise 3

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
```

## Exercise 4

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
```


## Exercise 5

*Your narrative answer here.*

## Exercise 6

Add code blocks as needed for this and remaining exercises.

## Exercise 7

## Exercise 8
