---
title: "Survey Results"
---

```{r setup, message=FALSE}
library(tidyverse)
theme_set(theme_bw())
```


```{r}
results <- tibble::tribble(
  ~which_harder, ~lab_hr, ~homework_hr,
             "Lab is much harder",       2,          1.5,
            "Lab is a bit harder",       1,         0.75,
            "Lab is a bit harder",     1.5,         0.75,
       "Homework is a bit harder",     1.5,            1,
       "Homework is a bit harder",       3,            2,
       "Homework is a bit harder",     2.5,          1.5,
       "Homework is a bit harder",    0.75,          1.1,
       "Homework is a bit harder",     1.5,            1,
            "Lab is a bit harder",       1,         0.75,
       "Homework is a bit harder",     1.5,          1.5,
       "Homework is a bit harder",       1,         1.25,
       "Homework is a bit harder",       1,            1,
            "Lab is a bit harder",     1.3,            1,
       "Homework is a bit harder",       1,          1.5,
       "Homework is a bit harder",    1.25,          0.5,
       "Homework is a bit harder",    0.75,            1,
            "Lab is a bit harder",       4,            3,
       "Homework is a bit harder",       3,          1.5,
            "Lab is a bit harder",     1.5,            1,
       "Homework is a bit harder",       2,            5,
            "Lab is a bit harder",     1.5,            1,
       "Homework is a bit harder",       1,            1,
            "Lab is a bit harder",       2,            1,
            "Lab is a bit harder",     2.5,          1.5,
            "Lab is a bit harder",       2,          0.5,
       "Homework is a bit harder",       2,          0.5,
            "Lab is a bit harder",     2.5,          1.5,
            "Lab is a bit harder",     1.1,            1,
       "Homework is a bit harder",       2,            1
  )
```

```{r which-is-harder}
results %>%
  count(which_harder) %>% 
  ggplot(aes(y = which_harder, x = n)) + geom_col()
results %>% 
  ggplot(aes(y = which_harder)) +
    geom_bar()
```

```{r lab_longer, fig.height=2, fig.width=6}
results %>%
  mutate(lab_longer = lab_hr - homework_hr) %>% 
  ggplot(aes(x = lab_longer)) +
    geom_vline(xintercept = 0, color = "#888888") +
    geom_dotplot(binwidth = .1) +
    scale_y_continuous(NULL, breaks = NULL) + # hide y axis
    labs(x = "Time taken by lab minus time taken by homework")
```

```{r}
results %>% 
  select(-which_harder) %>% 
  pivot_longer(everything()) %>% 
  ggplot(aes(y = name, x = value)) +
    geom_boxplot()
```

