---
title: "Problem-Solving, Collaboration, and Sad Charts"
author: "K Arnold, based on DSBox"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    self_contained: FALSE
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE, message=FALSE}
source("../slides-common.R")
slideSetup()
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

## Problem-Solving

* **Understand your data**: at the *input* and at *each step* in a pipeline.
  * Read the first row out loud. What does it say?
  * How many rows are there? What does each row represent?
* **Think about your goal**
  * What should the first row of my output be?
  * If I had to work out each value in that row by hand, what parts of the input would I need?
* **Take small steps**
  * Look at the results after each step
  * Work out your computation for one datum first, then go to all of them.

Data science is **not magic**. Deliberate application of concepts and strategies
will (eventually) bear fruit, no matter what language / library.

---

## Cooperation vs Collaboration

"It is also important for the teams to understand the difference between cooperation and collaboration.

* *Cooperation* is where the multiple tasks of a project are divided among the team members, but each person works independently.
* *Collaboration* is the process where the finished product is produced via interactions among all of the members of the group  working  together 

True training in teamwork will come from collaboration, not cooperation."

<br>

.right[
.small[
Ekblaw. [Effective Use Of Group Projects In Online Learning](https://files.eric.ed.gov/fulltext/EJ1106897.pdf). Contemporary Issues in Education Research. 2016
]
]

---

## Where we are

* We visualized. We wrangled. Now we'll get more practice bringing those together.
* Some VoiceThread notes published, more coming.
* Next week: start predictive modeling

This week: replicate and critique visuals

* Lab 5 (starting today): critique a vis we give.
* Discussion 3: critique a vis you find

* Quiz 5 on Thursday: no more infinite tries.

