
## Exercise 4: Mapping vs Faceting

Now let's look at workdays vs weekends (and holidays), which is encoded in the `workingday` variable, like in Exercise 1. Try the following.

1. Make a scatterplot like in Exercise 4, but map `shape` to `workingday`.
2. Try *faceting* by `workingday` instead.
3. Try swapping the roles of `rider_type` and `workingday` in the faceted scatterplot.
4. Try adjusting parameters for the faceting, considering whether you should use rows or columns, and whether you should use free or fixed y scales.

Once you're done, pick two plots to leave in this section and remove all the others. Describe the structure the each plot, and compare and contrast the value of the two plots. For which purpose is each one better? What about the design of the plot makes it fit that purpose?


# Exercise 5: Mapping vs Faceting

```{python}
show_plot(
  px.scatter(
    daily_rides,
    x="date", y="rides", color="rider_type",
    symbol="workingday",
    trendline="lowess",
    labels={"date": "Date", "rides": "Number of Rides", "rider_type": "Type of Rider"}
    )
    .update_traces(marker_size=3, marker_opacity=.5)
)
```


```{python}
show_plot(
  px.scatter(
    daily_rides,
    x="date", y="rides", color="rider_type",
    facet_col="workingday",
    trendline="lowess",
    labels={"date": "Date", "rides": "Number of Rides", "rider_type": "Type of Rider"}
    )
    .update_traces(marker_size=3, marker_opacity=.5)
    .update_yaxes(matches=None, showticklabels=True)
)
```
