---
title: "deps"
output: html_document
date: "2022-08-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
all_deps <- renv::dependencies(path = here::here())
```

```{r}
non_archive <- 
  all_deps |> 
  filter(!str_detect(Source, "archive"))

missing_pkgs <- non_archive |> 
  pull(Package) |> 
  unique() |> 
  setdiff(installed.packages()[,1])
semi_join(non_archive, tibble(Package = missing_pkgs), by = "Package") |>
  group_by(Package) |> slice_head(n = 1)
```

Ask Chris to install:

```{r}
ask_chris_to_install <- c("nasaweather", "prettydoc", "unvotes", "ggspatial", "ranger", "animation", "tidygeocoder", "fec12", "datasauRus", "directlabels", "maps", "mapview", "rnoaa", "vip", "openxlsx")
missing_pkgs |> setdiff(ask_chris_to_install)
ask_chris_to_install <- c(
  ask_chris_to_install, "ape"
)

```


Manual dev installs:

```{r}
install.packages("tufte")
install.packages("xaringan")
install.packages("xaringanExtra")
install.packages("xaringanthemer")

remotes::install_github("hadley/emo")
remotes::install_github("EvaMaeRey/flipbookr")
```

