---
title: "packages"
format: html
editor: visual
---

Existing packages

```{r}
old_packages <- c("anytime", "countdown", "fable", "fabletools", "fec12", "leafem", 
"leafpop", "mapview", "pamr", "regexplain", "satellite", "tsne", 
"urca", "xaringanExtra", "abd", "abind", "acepack", "ade4", "AER", 
"airports", "alr3", "alr4", "Amelia", "anytime", "ape", "arrayhelpers", 
"arrow", "ash", "AsioHeaders", "askpass", "assertthat", "audio", 
"available", "babynames", "backports", "base64enc", "bayesplot", 
"bdsmatrix", "beepr", "bench", "BH", "bibtex", "biglm", "BiocManager", 
"BiocParallel", "BiocVersion", "BioStatTutor", "bit", "bit64", 
"bitops", "blob", "bookdown", "bootstrap", "BradleyTerry2", "brew", 
"brglm", "bridgesampling", "brio", "brms", "Brobdingnag", "broom", 
"bslib", "cachem", "Cairo", "calendar", "callr", "CalvinBayes", 
"CalvinData", "car", "carData", "caret", "caTools", "cellranger", 
"checkmate", "cherryblossom", "circular", "classInt", "cli", 
"clipr", "clisymbols", "coda", "collapse", "colorspace", "colourpicker", 
"colourvalues", "commonmark", "config", "conflicted", "conquer", 
"coro", "corpcor", "corrgram", "corrplot", "covr", "cowplot", 
"cowsay", "cpp11", "crayon", "credentials", "crosstalk", "cubature", 
"curl", "d3heatmap", "DAAG", "dagitty", "data.table", "DataExplorer", 
"datawizard", "DBI", "dbplyr", "debugme", "deltaMethod", "dendextend", 
"desc", "deSolve", "Devore7", "devtools", "DHARMa", "DiagrammeR", 
"dials", "DiceDesign", "diffobj", "digest", "discrim", "distributional", 
"doParallel", "dotenv", "downlit", "downloader", "dplyr", "DT", 
"dtplyr", "dygraphs", "dynlm", "e1071", "effects", "ellipse", 
"ellipsis", "emmeans", "emo", "emoGG", "estimability", "etl", 
"evaluate", "expss", "extrafont", "extrafontdb", "fable", "fabletools", 
"factful", "FactoMineR", "fansi", "faraway", "farver", "fastmap", 
"fastR2", "fda", "fds", "feasts", "filelock", "fivethirtyeight", 
"flashClust", "flexdashboard", "FNN", "fontawesome", "fontBitstreamVera", 
"fontLiberation", "fontquiver", "forcats", "foreach", "forge", 
"formatR", "Formula", "fortunes", "fpp3", "freetypeharfbuzz", 
"fs", "furrr", "futile.logger", "futile.options", "future", "future.apply", 
"gamlss.dist", "gamm4", "gap", "gapminder", "gargle", "gbRd", 
"gclus", "gdata", "gdtools", "geepack", "generics", "geojsonsf", 
"geometries", "gert", "GGally", "gganimate", "ggdag", "ggdendro", 
"ggdist", "ggeffects", "ggforce", "ggformula", "ggmap", "ggmcmc", 
"ggmosaic", "ggplot2", "ggplot2movies", "ggraph", "ggrepel", 
"ggridges", "ggspatial", "ggstance", "ggthemes", "gh", "git2r", 
"gitcreds", "glmmTMB", "glmnet", "globals", "glue", "googledrive", 
"googlePolylines", "googlesheets", "googlesheets4", "gower", 
"GPfit", "gplots", "gratia", "gridExtra", "gtable", "gtools", 
"hardhat", "haven", "HDInterval", "hdrcde", "here", "hexbin", 
"highlight", "highr", "Hmisc", "hms", "htmlTable", "htmltools", 
"htmlwidgets", "httpuv", "httr", "hunspell", "huxtable", "ids", 
"igraph", "infer", "influenceR", "ini", "inline", "insight", 
"inum", "invgamma", "ipred", "ISLR", "isoband", "ISOcodes", "iterators", 
"janeaustenr", "janitor", "jpeg", "jquerylib", "jsonify", "jsonlite", 
"kableExtra", "kernlab", "kknn", "knitr", "ks", "labeling", "labelled", 
"Lahman", "lambda.r", "later", "latticeExtra", "lava", "lazyeval", 
"leaflet", "leaflet.providers", "leaps", "learnr", "lhs", "libcoin", 
"lifecycle", "listenv", "listviewer", "lme4", "lmtest", "lobstr", 
"locfit", "Lock5withR", "loo", "lubridate", "luz", "macleish", 
"maditr", "magick", "magrittr", "manipulate", "mapdeck", "mapproj", 
"maps", "maptools", "markdown", "MatchIt", "MatrixModels", "matrixStats", 
"maxLik", "mclust", "mcmc", "MCMCpack", "mdsr", "memoise", "mime", 
"miniUI", "minqa", "misc3d", "miscTools", "mitools", "mixOmics", 
"modeldata", "ModelMetrics", "modelr", "mosaic", "mosaicCalc", 
"mosaicCore", "mosaicData", "multcomp", "multicool", "MuMIn", 
"munsell", "mvnfast", "mvtnorm", "naniar", "nasaweather", "networkD3", 
"NeuralNetTools", "NHANES", "nhanesA", "nleqslv", "nloptr", "NLP", 
"norm", "numDeriv", "nycflights13", "oibiostat", "openintro", 
"openssl", "openxlsx", "optimx", "ordinal", "packrat", "pagedown", 
"palmerpenguins", "pander", "parallelly", "parsedate", "parsnip", 
"partykit", "patchwork", "pbkrtest", "pcaPP", "permute", "pillar", 
"pingr", "pins", "pixmap", "pkgbuild", "pkgconfig", "pkgdown", 
"pkgload", "plm", "plogr", "plot3D", "plotly", "pls", "plyr", 
"png", "polyclip", "posterior", "pracma", "praise", "prettydoc", 
"prettymapr", "prettyunits", "pROC", "processx", "prodlim", "productplots", 
"profileModel", "profmem", "profvis", "progress", "progressr", 
"projpred", "promises", "proto", "proxy", "pryr", "ps", "pscl", 
"pspearman", "purrr", "qap", "qgam", "qualtRics", "quantreg", 
"qvcalc", "R.cache", "R.methodsS3", "R.oo", "R.utils", "r2d3", 
"R2jags", "R2WinBUGS", "R6", "ragg", "rainbow", "randomForest", 
"ranger", "rapidjsonr", "rappdirs", "rARPACK", "raster", "rbibutils", 
"rclipboard", "rcmdcheck", "RColorBrewer", "Rcpp", "RcppArmadillo", 
"RcppEigen", "RcppParallel", "RcppProgress", "RcppTOML", "RCurl", 
"Rdpack", "reactable", "reactlog", "reactR", "readr", "readxl", 
"recipes", "registry", "rematch", "rematch2", "remotes", "renv", 
"repr", "reprex", "reshape", "reshape2", "rethinking", "reticulate", 
"rex", "rgdal", "RgoogleMaps", "rio", "rjags", "rjp", "rjson", 
"RJSONIO", "rlang", "RMariaDB", "rmarkdown", "rmsfact", "RMySQL", 
"rngtools", "ROCR", "rosm", "roxygen2", "rpart.plot", "rprojroot", 
"rsample", "rsconnect", "RSpectra", "RSQLite", "rsrecovr", "rstan", 
"rstanarm", "rstantools", "rstudioapi", "rticles", "Rttf2pt1", 
"runjags", "RVAideMemoire", "rversions", "rvest", "s2", "s245", 
"sandwich", "sass", "scales", "scatterplot3d", "selectr", "seriation", 
"servr", "sessioninfo", "sf", "sfheaders", "sfsmisc", "shape", 
"shiny", "shinydashboard", "shinyjs", "shinystan", "shinytest", 
"shinythemes", "showimage", "showtext", "showtextdb", "sjlabelled", 
"skimr", "slam", "slider", "snakecase", "snow", "SnowballC", 
"sourcetools", "sp", "sparklyr", "SparseM", "spatialwidget", 
"SQUAREM", "StanHeaders", "stargazer", "Stat2Data", "statmod", 
"StatTutor", "stopwords", "stringdist", "stringi", "stringr", 
"styler", "submitr", "survey", "svglite", "svUnit", "sys", "sysfonts", 
"systemfonts", "TeachingDemos", "tensorA", "tensorflow", "terra", 
"testthat", "textdata", "textshaping", "tfautograph", "tfruns", 
"TH.data", "threejs", "tibble", "tidybayes", "tidycensus", "tidygeocoder", 
"tidygraph", "tidymodels", "tidyposterior", "tidypredict", "tidyr", 
"tidyselect", "tidytext", "tidyverse", "tigris", "timeDate", 
"tinytex", "tm", "TMB", "tokenizers", "torch", "triangle", "tsibble", 
"tsibbledata", "TSP", "tufte", "tune", "tweedie", "tweenr", "tzdb", 
"ucminf", "udapi", "units", "UpSetR", "urca", "usdata", "usethis", 
"utf8", "uuid", "V8", "vcd", "vctrs", "vegan", "VGAM", "viridis", 
"viridisLite", "visdat", "visNetwork", "visualize", "vroom", 
"waldo", "warp", "webdriver", "webshot", "websocket", "whisker", 
"withr", "wk", "wooldridge", "wordcloud", "workflows", "workflowsets", 
"wru", "xaringan", "xaringanthemer", "xfun", "xgboost", "xkcd", 
"XML", "xml2", "xopen", "xtable", "xts", "yaml", "yardstick", 
"yesno", "zeallot", "Zelig", "zip", "zoo", "base", "boot", "class", 
"cluster", "codetools", "compiler", "datasets", "foreign", "graphics", 
"grDevices", "grid", "KernSmooth", "lattice", "MASS", "Matrix", 
"methods", "mgcv", "nlme", "nnet", "parallel", "rpart", "spatial", 
"splines", "stats", "stats4", "survival", "tcltk", "tools", "utils"
)
```

Current packages

```{r}
pkgs <- installed.packages()[, 1]
names(pkgs) <- NULL
```

Diff

```{r}
paste(setdiff(old_packages, pkgs), collapse = "\n") |> cat()
```
