---
title: "Tidy Scratch"
author: "K Arnold"
date: "10/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(mdsr)
library(googlesheets4)
```


```{r}
hiv_key <- "1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA"
hiv_raw <- 
  read_sheet(hiv_key) 
hiv <- hiv_raw %>% 
  rename(Country = 1) %>%
  #filter(
  #  Country %in% c("United States", "France", "South Africa")
  #) %>%
  select(Country, `1987`, `1997`, `2007`) %>%
  mutate(across(matches("[0-9]"), as.double))
```


```{r}
hiv %>% 
  filter(!is.na(`2007`)) %>% 
  ggplot(aes(y = Country, x = `2007`)) + geom_col()
```

## Gapminder Population Wide

https://docs.google.com/spreadsheets/d/14_suWY8fCPEXV0MH7ZQMZ-KndzMVsSsA5HdR-7WqAC0/edit#gid=1008305493

```{r}
# Gapminder columns
gapminder_pop_wide <- read_csv(
  "https://docs.google.com/spreadsheets/d/14_suWY8fCPEXV0MH7ZQMZ-KndzMVsSsA5HdR-7WqAC0/export?format=csv&gid=1008305493",
  skip = 2)
```


```{r}
library(mdsr)
```

```{r}
ordway_birds
```


## Baseball

```{r}
library(Lahman)
```

```{r}
Teams
```


---

## College Labor Market Wages

```{r}
# https://www.newyorkfed.org/medialibrary/media/research/college-labor-market/labor-market-for-recent-college-grads.xlsx?la=en
openxlsx::read.xlsx(
  "~/Downloads/labor-market-for-recent-college-grads.xlsx",
  sheet = 5,
  startRow = 14)
```

