
```{r eval=FALSE}
usethis::use_git_config(scope = "user", "credential.helper" = "cache --timeout=10000000")
```


```{r}
library(tidyverse)
library(directlabels)
theme_set(theme_bw())
```

```{r}
dir.create("data")
covid_data_filename <- "data/owid-covid-data.csv"
if (!file.exists(covid_data_filename)) {
  httr::GET(
    "https://covid.ourworldindata.org/data/owid-covid-data.csv",
    httr::write_disk(covid_data_filename)
  )
}
```


```{r}
owid_covid_data <- read_csv(covid_data_filename, col_types = cols(
  iso_code = col_character(),
  continent = col_character(),
  location = col_character(),
  date = col_date(format = ""),
  total_cases = col_double(),
  new_cases = col_double(),
  new_cases_smoothed = col_double(),
  total_deaths = col_double(),
  new_deaths = col_double(),
  new_deaths_smoothed = col_double(),
  total_cases_per_million = col_double(),
  new_cases_per_million = col_double(),
  new_cases_smoothed_per_million = col_double(),
  total_deaths_per_million = col_double(),
  new_deaths_per_million = col_double(),
  new_deaths_smoothed_per_million = col_double(),
  new_tests = col_double(),
  total_tests = col_double(),
  total_tests_per_thousand = col_double(),
  new_tests_per_thousand = col_double(),
  new_tests_smoothed = col_double(),
  new_tests_smoothed_per_thousand = col_double(),
  tests_per_case = col_double(),
  positive_rate = col_double(),
  tests_units = col_character(),
  stringency_index = col_double(),
  population = col_double(),
  population_density = col_double(),
  median_age = col_double(),
  aged_65_older = col_double(),
  aged_70_older = col_double(),
  gdp_per_capita = col_double(),
  extreme_poverty = col_double(),
  cardiovasc_death_rate = col_double(),
  diabetes_prevalence = col_double(),
  female_smokers = col_double(),
  male_smokers = col_double(),
  handwashing_facilities = col_double(),
  hospital_beds_per_thousand = col_double(),
  life_expectancy = col_double(),
  human_development_index = col_double()
))
```

```{r}
library(skimr)
skim(owid_covid_data)
```


```{r}
countries <- c(
  "China",
  "France",
  "United Kingdom",
  "United States",
  "Turkey"
)

owid_covid_data$location %>% unique() %>% setdiff(countries, .)
```

```{r}
latest_data <- owid_covid_data %>% 
  group_by(location) %>%
  arrange(date) %>%
  filter(!is.na(total_tests)) %>% 
  slice_tail()
latest_data
```

```{r}
ggplot(latest_data, aes(x = total_tests_per_thousand, y = reorder(continent, total_tests_per_thousand, median))) +
  geom_boxplot()
```

```{r}
latest_data$total_tests_per_thousand %>% skim()
```

```{r}
testing_countries <- latest_data %>% filter(total_tests_per_thousand > 15) %>% pull(location)
top_testers <- latest_data %>% 
  filter(total_cases > 10000) %>% 
  arrange(desc(total_tests_per_thousand)) %>% head(10)
```



```{r}
latest_data %>% arrange(desc(total_tests_per_thousand)) %>% select(location, total_cases, total_tests)
```


```{r}
owid_covid_data %>% 
  filter(location %in% top_testers$location) %>% #c("Denmark", "United States", "New Zealand")) %>% 
  ggplot(aes(x = date, y = total_tests_per_thousand, color = location)) +
    geom_line()
    #geom_dl(aes(label = location), method = list("last.points")) +
    #scale_color_discrete(guide = "none")
```

