## Classifier Metrics and Fairness

Consider Google's "[Simulating Loan Thresholds](http://research.google.com/bigpicture/attacking-discrimination-in-ml/)" activity that we studied in Exercise 9.

In this activity, we're considering a *predictive model* that is attempting to predict whether an applicant will repay a loan.
In the real world, we only get to observe whether someone repays a loan if that loan was actually given to them.
But this hypothetical scenario assumes that we know something that is not knowable: who among the people who were *not* given a loan would have repaid it if, counter to fact, they had been accepted.
(This is the distinction between light and dark grey people in the visualization.)

### Simplified Situation

Considering just the situation with the single group for now:

1. What credit score threshold maximizes the number of correct decisions?

2. What threshold maximizes profit? (The app assumes a marginal gain of $300 for 
each loan repaid and a loss of $700 for each loan default.)

3. Are your answers to #1 and #2 the same? Why or why not? <!-- Use the language of “False Positive” and “False Negative”. -->

4. The app doesn't let you experiment with this, but suppose repaid loans had 
a marginal benefit of \$400 and defaulted loans a marginal cost of only \$600.

    a. Would that lead a profit-maximizer to increase or decrease the threshold?
    Why?

    b. How would the threshold change if you are maximizing correct decisions?

### Different groups

**Don’t click the red buttons until directed.** Instead, just drag the threshold sliders.

5.	Adjust the thresholds to maximize the profit that the bank gets for each
group individually.

    - What are the resulting thresholds for the two groups? (Check your answer
by clicking on the red “Max Profit” button.)
    - At those thresholds, which group is offered more loans? 
    - Of the loans that were offered, which group repays more of those loans?
    - What is the resulting profit for the bank?
    - Is that fair? Explain.

6.	Adjust the thresholds to maximize profit under the constraint that blue and
orange must have the same threshold. (This is tricky in the UI; hint: it must be
between the two thresholds you found in the previous exercise.) Answer the same
five questions (a-e) as in the previous exercise. Then check your answer by
clicking the "Group Unaware" button.

7.	Starting at the "Group Unaware" thresholds, change the threshold on the
orange group to increase its Positive Rate to match the Positive Rate of the
blue group.

    - What happens to the True Positive Rate?
    - What happens to the bank’s profit?
    - Is that good? Explain.

8. Explain each of the objectives in your own words. (You may want to explore the "Demographic Parity" and "Equal Opportunity" objectives by clicking their buttons.) For each one, identify *who* would prefer that objective. For example, a big bank might prefer the "max profit" objective because they're legally required to make decisions to maximize value to their shareholders. Who might prefer "group unaware"? "Demographic parity"? "Equal opportunity"?

  - Which of the objectives do you think is most "right"?

9. The authors of the interactive visualization seem to
have a favorite among these objectives. What reasons might someone have to agree
or disagree with their assessment?

